version: '3.9'

services:
  api:
    container_name: meu-teste-tecnico
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        node_env: dev
    volumes:
      - .:/home/meu-teste-tecnico
      - /home/meu-teste-tecnico/node_modules
